// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ProjectStatus is an object representing the database table.
type ProjectStatus struct {
	ID           int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	ProjectID    int64     `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	Name         string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Color        string    `boil:"color" json:"color" toml:"color" yaml:"color"`
	DisplayOrder int64     `boil:"display_order" json:"display_order" toml:"display_order" yaml:"display_order"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *projectStatusR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L projectStatusL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProjectStatusColumns = struct {
	ID           string
	ProjectID    string
	Name         string
	Color        string
	DisplayOrder string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	ProjectID:    "project_id",
	Name:         "name",
	Color:        "color",
	DisplayOrder: "display_order",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

// Generated where

var ProjectStatusWhere = struct {
	ID           whereHelperint64
	ProjectID    whereHelperint64
	Name         whereHelperstring
	Color        whereHelperstring
	DisplayOrder whereHelperint64
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	ID:           whereHelperint64{field: "\"project_status\".\"id\""},
	ProjectID:    whereHelperint64{field: "\"project_status\".\"project_id\""},
	Name:         whereHelperstring{field: "\"project_status\".\"name\""},
	Color:        whereHelperstring{field: "\"project_status\".\"color\""},
	DisplayOrder: whereHelperint64{field: "\"project_status\".\"display_order\""},
	CreatedAt:    whereHelpertime_Time{field: "\"project_status\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"project_status\".\"updated_at\""},
}

// ProjectStatusRels is where relationship names are stored.
var ProjectStatusRels = struct {
}{}

// projectStatusR is where relationships are stored.
type projectStatusR struct {
}

// NewStruct creates a new relationship struct
func (*projectStatusR) NewStruct() *projectStatusR {
	return &projectStatusR{}
}

// projectStatusL is where Load methods for each relationship are stored.
type projectStatusL struct{}

var (
	projectStatusAllColumns            = []string{"id", "project_id", "name", "color", "display_order", "created_at", "updated_at"}
	projectStatusColumnsWithoutDefault = []string{"project_id", "name", "color", "display_order", "created_at", "updated_at"}
	projectStatusColumnsWithDefault    = []string{"id"}
	projectStatusPrimaryKeyColumns     = []string{"id"}
)

type (
	// ProjectStatusSlice is an alias for a slice of pointers to ProjectStatus.
	// This should generally be used opposed to []ProjectStatus.
	ProjectStatusSlice []*ProjectStatus
	// ProjectStatusHook is the signature for custom ProjectStatus hook methods
	ProjectStatusHook func(context.Context, boil.ContextExecutor, *ProjectStatus) error

	projectStatusQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	projectStatusType                 = reflect.TypeOf(&ProjectStatus{})
	projectStatusMapping              = queries.MakeStructMapping(projectStatusType)
	projectStatusPrimaryKeyMapping, _ = queries.BindMapping(projectStatusType, projectStatusMapping, projectStatusPrimaryKeyColumns)
	projectStatusInsertCacheMut       sync.RWMutex
	projectStatusInsertCache          = make(map[string]insertCache)
	projectStatusUpdateCacheMut       sync.RWMutex
	projectStatusUpdateCache          = make(map[string]updateCache)
	projectStatusUpsertCacheMut       sync.RWMutex
	projectStatusUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var projectStatusBeforeInsertHooks []ProjectStatusHook
var projectStatusBeforeUpdateHooks []ProjectStatusHook
var projectStatusBeforeDeleteHooks []ProjectStatusHook
var projectStatusBeforeUpsertHooks []ProjectStatusHook

var projectStatusAfterInsertHooks []ProjectStatusHook
var projectStatusAfterSelectHooks []ProjectStatusHook
var projectStatusAfterUpdateHooks []ProjectStatusHook
var projectStatusAfterDeleteHooks []ProjectStatusHook
var projectStatusAfterUpsertHooks []ProjectStatusHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ProjectStatus) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ProjectStatus) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ProjectStatus) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ProjectStatus) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ProjectStatus) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ProjectStatus) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ProjectStatus) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ProjectStatus) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ProjectStatus) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectStatusAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProjectStatusHook registers your hook function for all future operations.
func AddProjectStatusHook(hookPoint boil.HookPoint, projectStatusHook ProjectStatusHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		projectStatusBeforeInsertHooks = append(projectStatusBeforeInsertHooks, projectStatusHook)
	case boil.BeforeUpdateHook:
		projectStatusBeforeUpdateHooks = append(projectStatusBeforeUpdateHooks, projectStatusHook)
	case boil.BeforeDeleteHook:
		projectStatusBeforeDeleteHooks = append(projectStatusBeforeDeleteHooks, projectStatusHook)
	case boil.BeforeUpsertHook:
		projectStatusBeforeUpsertHooks = append(projectStatusBeforeUpsertHooks, projectStatusHook)
	case boil.AfterInsertHook:
		projectStatusAfterInsertHooks = append(projectStatusAfterInsertHooks, projectStatusHook)
	case boil.AfterSelectHook:
		projectStatusAfterSelectHooks = append(projectStatusAfterSelectHooks, projectStatusHook)
	case boil.AfterUpdateHook:
		projectStatusAfterUpdateHooks = append(projectStatusAfterUpdateHooks, projectStatusHook)
	case boil.AfterDeleteHook:
		projectStatusAfterDeleteHooks = append(projectStatusAfterDeleteHooks, projectStatusHook)
	case boil.AfterUpsertHook:
		projectStatusAfterUpsertHooks = append(projectStatusAfterUpsertHooks, projectStatusHook)
	}
}

// One returns a single projectStatus record from the query.
func (q projectStatusQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ProjectStatus, error) {
	o := &ProjectStatus{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for project_status")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ProjectStatus records from the query.
func (q projectStatusQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProjectStatusSlice, error) {
	var o []*ProjectStatus

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ProjectStatus slice")
	}

	if len(projectStatusAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ProjectStatus records in the query.
func (q projectStatusQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count project_status rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q projectStatusQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if project_status exists")
	}

	return count > 0, nil
}

// ProjectStatuses retrieves all the records using an executor.
func ProjectStatuses(mods ...qm.QueryMod) projectStatusQuery {
	mods = append(mods, qm.From("\"project_status\""))
	return projectStatusQuery{NewQuery(mods...)}
}

// FindProjectStatus retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProjectStatus(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ProjectStatus, error) {
	projectStatusObj := &ProjectStatus{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"project_status\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, projectStatusObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from project_status")
	}

	return projectStatusObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ProjectStatus) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no project_status provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectStatusColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	projectStatusInsertCacheMut.RLock()
	cache, cached := projectStatusInsertCache[key]
	projectStatusInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			projectStatusAllColumns,
			projectStatusColumnsWithDefault,
			projectStatusColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(projectStatusType, projectStatusMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(projectStatusType, projectStatusMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"project_status\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"project_status\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT \"%s\" FROM \"project_status\" WHERE %s", strings.Join(returnColumns, "\",\""), strmangle.WhereClause("\"", "\"", 0, projectStatusPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into project_status")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == projectStatusMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for project_status")
	}

CacheNoHooks:
	if !cached {
		projectStatusInsertCacheMut.Lock()
		projectStatusInsertCache[key] = cache
		projectStatusInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ProjectStatus.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ProjectStatus) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	projectStatusUpdateCacheMut.RLock()
	cache, cached := projectStatusUpdateCache[key]
	projectStatusUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			projectStatusAllColumns,
			projectStatusPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update project_status, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"project_status\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, projectStatusPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(projectStatusType, projectStatusMapping, append(wl, projectStatusPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update project_status row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for project_status")
	}

	if !cached {
		projectStatusUpdateCacheMut.Lock()
		projectStatusUpdateCache[key] = cache
		projectStatusUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q projectStatusQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for project_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for project_status")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProjectStatusSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"project_status\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, projectStatusPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in projectStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all projectStatus")
	}
	return rowsAff, nil
}

// Delete deletes a single ProjectStatus record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ProjectStatus) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ProjectStatus provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), projectStatusPrimaryKeyMapping)
	sql := "DELETE FROM \"project_status\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from project_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for project_status")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q projectStatusQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no projectStatusQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from project_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for project_status")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProjectStatusSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(projectStatusBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"project_status\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, projectStatusPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from projectStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for project_status")
	}

	if len(projectStatusAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ProjectStatus) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProjectStatus(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProjectStatusSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProjectStatusSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"project_status\".* FROM \"project_status\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, projectStatusPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ProjectStatusSlice")
	}

	*o = slice

	return nil
}

// ProjectStatusExists checks if the ProjectStatus row exists.
func ProjectStatusExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"project_status\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if project_status exists")
	}

	return exists, nil
}
